BASE_URL = 'https://stellarburgers.nomoreparties.site/'
LOGIN_URL = BASE_URL + 'login'
FORGOT_PASSWORD_URL = BASE_URL + 'forgot-password'
RESET_PASSWORD_URL = BASE_URL + 'reset-password'
PROFILE_URL = BASE_URL + 'account/profile'
ORDER_HISTORY = BASE_URL + 'account/order-history'
FEED_URL = BASE_URL + 'feed'
